version: '3.8'
services:
  ng1:
    image: nginx:latest
    container_name: ng1
    restart: unless-stopped
    ports:
      - "9191:80"  # Map port 9191 on the host to port 80 in the container
    volumes:
      - ./vol:/usr/share/nginx/html  # Mount the vol folder to the Nginx HTML folder

  ng2:
    image: nginx:latest
    container_name: ng2
    restart: unless-stopped
    ports:
      - "8080:80"  # Map port 8080 on the host to port 80 in the container
    volumes:
      - ./vol:/usr/share/nginx/html  # Mount the vol folder to the Nginx HTML folder
